ShopWebUI/Controllers/PhotoController.cs
using Shop.BLL.BizModels;
using Shop.BLL.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopWebUI.Controllers
{
    public class PhotoController : Controller
    {
        // GET: Photo        
        IGenericService<PhotoDTO, int> servicePhoto;
        IGenericService<ProductDTO, int> serviceProduct;
        public PhotoController(IGenericService<PhotoDTO, int> servicePhoto,
            IGenericService<ProductDTO, int> serviceProduct)
        {
            this.servicePhoto = servicePhoto;
            this.serviceProduct = serviceProduct;
        }
        public ActionResult Index(int id = 1)
        {
            var product = serviceProduct.GetObjInstance(id);
            ViewBag.Product = product;// $"{product.ProductName}; Price-{product.Price}";
            var model = servicePhoto.FindBy(p => p.ProductId == id);
            return View(model);
        }
        public ActionResult Upload(int id = 1)
        {
            var model = id;
            return View(model);
        }
        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> fileUploadMulti)//fileUploadMulti обязательно совпадет с input
        {
            string idstr = Request.Params["id"];
            int id = Convert.ToInt32(idstr);
            foreach (var file in fileUploadMulti)
            {
                if (file == null) continue;
                string path = AppDomain.CurrentDomain.BaseDirectory + "img/";
                string filename = Path.GetFileName(file.FileName);
                string newfilename = Guid.NewGuid().ToString() + Path.GetExtension(filename);
                if (filename != null)
                {
                    file.SaveAs(Path.Combine(path, newfilename));
                    PhotoDTO photo = new PhotoDTO
                    {
                        ProductId = id,
                        PhotoPath = "/img/" + newfilename
                    };
                    servicePhoto.Add(photo);
                }
            }
            return RedirectToAction("Index", new { id = id });
        }
        public ActionResult Delete(int id = 1)
        {
            servicePhoto.Delete(id);
            return Json("OK");
        }
    }
}

ShopWebUI/Views/Photo/Index.cshtml
@model IEnumerable<Shop.BLL.BizModels.PhotoDTO>

@{
    ViewBag.Title = "Index";
}
<h3>
    @ViewBag.Product.ProductName; Price - @ViewBag.Product.Price
</h3>
@Html.ActionLink("Add photo", "Upload", "Photo", new { id = ViewBag.Product.ProductId }, new { @class = "btn btn-warning" })
@if (Model.Count() > 0)
{
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 col-sm-6 col btn-xs col-xs-12">
                    <hr />
                    <img src="@item.PhotoPath" height="200" />
                    <hr />
                    <a href="#" class="btn btn-danger btn-sm btndel-photo"
                       data-photoid="@item.PhotoId">
                        Delete photo
                    </a>
                </div>
            }
        </div>
    </div>
}
else
{
    <h3>No photo</h3>
}
@section Script{
    <script>
    $(function(){
        $('.btndel-photo').click(function () {
            let id = $(this).attr('data-photoid')
            if (confirm('Are you sure?')) {
                $.ajax({
                    url: "@Url.Action("Delete","Photo")",
                    type: 'POST',
                    data: { id: id },
                    success: function (data) {
                        if (data == "OK") {
                            window.location.href = "@Url.Action("Index","Photo",new {id=ViewBag.Product.ProductId })";
                        }
                        else
                            alert("Error on server");
                    },
                    error: function (data) {
                        alert(data);
                    }
                });
            }
        })
    })
    </script>
}

ShopWebUI/Views/Photo/Upload.cshtml
    @model int
@{
    ViewBag.Title = "Upload";
}

<h2>Upload photos</h2>

@using (Html.BeginForm("Upload", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="text" name="id" value="@Model" hidden />
    <input type="file" name="fileUploadMulti" multiple />
    <input type="submit" name="Submit" id="SubmitSingle" value="Upload" />
}