ShopWebUI/Controllers/ProductFindController.cs
using Shop.BLL.BizModels;
using Shop.BLL.Services;
using ShopWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopWebUI.Controllers
{
    public class ProductFindController : Controller
    {
        IGenericService<CategoryDTO, int> categoryService;
        IGenericService<ManufacturerDTO, int> manufacturerService;
        IGenericService<ProductDTO, int> productService;
        IGenericService<PhotoDTO, int> photoService;


        public ProductFindController(IGenericService<CategoryDTO, int> categoryService,
                  IGenericService<ManufacturerDTO, int> manufacturerService,
                  IGenericService<ProductDTO, int> productService,
                  IGenericService<PhotoDTO, int> photoService)
        {
            this.categoryService = categoryService;
            this.manufacturerService = manufacturerService;
            this.productService = productService;
            this.photoService = photoService;
        }
        // GET: ProductFind
        public ActionResult Index()
        {
            ViewModelProductFind model = new ViewModelProductFind(categoryService, manufacturerService);            
            return View(model);
        }
        [HttpPost]
        public ActionResult Index(ViewModelProductFind viewModel)
        {
            TempData["dataModel"] = viewModel;
            return Json("OK");
            //ViewModelProductFind model = new ViewModelProductFind(categoryService, manufacturerService);
            
        }
        public ActionResult ProductByFilter()
        {
            ViewModelProductFind filter = null;
            if(TempData["dataModel"]!=null)
            {
                filter = (ViewModelProductFind)TempData["dataModel"];
            }
            ViewModelProductByFilter model = new ViewModelProductByFilter(productService, photoService, filter);
            return PartialView(model);
        }
        public ActionResult ProductDefault()
        {
            var model = new ViewModelProductDefault(productService, photoService);
            return PartialView(model);
        }
    }
}

ShopWebUI/Views/ProductFind/Index.cshtml
@using ShopWebUI.Models
@model ViewModelProductFind
@{
    ViewBag.Title = "Find Product";
}

<h2>Index</h2>
@using (Html.BeginForm())
{
    <div class="container">
        <div class="row">
            <div class="col-sm-3">

                <div class="container-fluid">
                    <div class="row">
                        Manufacturer
                        <div class="col-sm-12">
                            @for (int i = 0; i < Model.ManufacturerSelect.Count; i++)
                            {
                                <div>
                                    @Html.HiddenFor(x => Model.ManufacturerSelect[i].ManufacturerId)
                                    @Html.CheckBoxFor(x => Model.ManufacturerSelect[i].IsCheck)
                                    @Html.DisplayFor(x => Model.ManufacturerSelect[i].ManufacturerName)
                                    @Html.HiddenFor(x => Model.ManufacturerSelect[i].ManufacturerName)
                                </div>
                            }


                        </div>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="row">
                        Category
                        <div class="col-sm-12">
                            @for (int i = 0; i < Model.CategorySelect.Count; i++)
                            {
                                <div>
                                    @Html.HiddenFor(x => Model.CategorySelect[i].CategoryId)
                                    @Html.CheckBoxFor(x => Model.CategorySelect[i].IsCheck)
                                    @Html.DisplayFor(x => Model.CategorySelect[i].CategoryName)
                                    @Html.HiddenFor(x => Model.CategorySelect[i].CategoryName)
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-9">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-1">
                            <button id="find" type="submit" class="btn btn-sm btn-warning">Find</button>
                        </div>      <div class="col-sm-9">
                            @Html.EditorFor(t => t.ProductName, new { htmlAttributes = new { @class = "form-control w-100",
                                                                    placeholder="Input part name goods"} } )
                        </div>
                        
                        <div class="col-sm-2">
                            @Html.ActionLink("Show Cart", "ShowCart", "Cart", null, new { @class = "btn btn-sm btn-success" })
                        </div>

                    </div>
                    <div class="row">
                        <div id="goods" class="col-sm-12">

                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>
}

@section Script
{
    <script type="text/javascript">

        $(function () {
            window.onload = function () {
                $('#goods').load("@Url.Action("ProductDefault","ProductFind")");
            }

            $('body').on('click', '.btn-cart', function (e) {
                e.preventDefault();
                $.ajax({
                    url:"@Url.Action("AddToCart", "Cart")",
                    type: 'POST',
                    data: {
                        id: $(this).attr('data-goodid'), returnUrl: 'ProductFind' }
                })
            })

            $('#find').click(function (e) {
                e.preventDefault();
                let dataForm = $('form').serialize();

                 $.ajax({
                    url: "@Url.Action("Index", "ProductFind")",
                    type: 'POST',
                    data: dataForm,
                    success: function (data) {
                        if (data == "OK") {
                            $('#goods').load("@Url.Action("ProductByFilter","ProductFind")");
                        }
                        else
                            alert("Error on server");
                    },
                    error: function (data) {
                        alert(data);
                    }

                });
            })
        });
    </script>
}

ShopWebUI/Views/ProductFind/ProductByFilter.cshtml
@using ShopWebUI.Models
@model ViewModelProductByFilter

@foreach (var item in Model.ListProductInfo)
{
    <div class="col-md-4 col-sm-6 col-xs-12">
        <hr/>
        <img src="@item.PhotoPath" height="200"/>
        <hr/>
        <a href="#" class="btn btn-danger btn-sm"
           data-goodid="@item.ProductId">
            @item.ProductName
        </a>
        <br/>
        <a href="#" class="btn btn-warning btn-sm btn-cart"
           data-goodid="@item.ProductId">
            Add to cart
        </a>           
    </div>
}

ShopWebUI/Views/ProductFind/ProductDefault.cshtml
@using ShopWebUI.Models
@model ViewModelProductDefault

@foreach (var item in Model.ListProductInfo)
{

    <div class="col-md-4 col-sm-6 col-xs-12">
        <hr />
        
            <img src="@item.PhotoPath" height="200" />
            <hr />
            <a href="#" class="btn btn-danger btn-sm"
               data-goodid="@item.ProductId">
                @item.ProductName
            </a>
            <br />
            <a href="#" class="btn btn-warning btn-sm btn-cart"
               data-goodid="@item.ProductId">
                Add to cart
            </a>        
    </div>
}